// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

"use strict";

{% include "Helpers.jsm" %}


{% include "Records.jsm" %}

{% include "TopLevelFunctions.jsm" %}