// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

#ifndef mozilla_dom_ArithmeticScaffolding_h
#define mozilla_dom_ArithmeticScaffolding_h

#include "mozilla/ErrorResult.h"
#include "mozilla/dom/RootedDictionary.h"
#include "mozilla/dom/TypedArray.h"
#include "mozilla/dom/UniFFIRustCallResultBinding.h"
#include "UniFFI.h"

// Scaffolding functions from UniFFI
extern "C" {
uint64_t arithmetic_475f_add(uint64_t, uint64_t, RustCallStatus*);

uint64_t arithmetic_475f_sub(uint64_t, uint64_t, RustCallStatus*);

uint64_t arithmetic_475f_div(uint64_t, uint64_t, RustCallStatus*);

int8_t arithmetic_475f_equal(uint64_t, uint64_t, RustCallStatus*);

}

namespace mozilla::dom {

class GlobalObject;

class ArithmeticScaffolding {
  public:
  static already_AddRefed<Promise> Arithmetic475fAdd(const GlobalObject& aUniFFIGlobal,const uint64_t& a, const uint64_t& b,
  ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> Arithmetic475fSub(const GlobalObject& aUniFFIGlobal,const uint64_t& a, const uint64_t& b,
  ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> Arithmetic475fDiv(const GlobalObject& aUniFFIGlobal,const uint64_t& dividend, const uint64_t& divisor,
  ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> Arithmetic475fEqual(const GlobalObject& aUniFFIGlobal,const uint64_t& a, const uint64_t& b,
  ErrorResult& aUniFFIErrorResult);
};

}  // namespace mozilla::dom

#endif  // mozilla_dom_ArithmeticScaffolding_h