// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

#ifndef mozilla_dom_GeometryScaffolding_h
#define mozilla_dom_GeometryScaffolding_h

#include "mozilla/ErrorResult.h"
#include "mozilla/dom/RootedDictionary.h"
#include "mozilla/dom/TypedArray.h"
#include "mozilla/dom/UniFFIRustCallResultBinding.h"
#include "UniFFI.h"

// Scaffolding functions from UniFFI
extern "C" {
double geometry_eb69_gradient(RustBuffer, RustCallStatus*);

RustBuffer geometry_eb69_intersection(RustBuffer, RustBuffer, RustCallStatus*);

}

namespace mozilla::dom {

class GlobalObject;

class GeometryScaffolding {
  public:
  static already_AddRefed<Promise> GeometryEb69Gradient(const GlobalObject& aUniFFIGlobal,const ArrayBuffer& ln,
  ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> GeometryEb69Intersection(const GlobalObject& aUniFFIGlobal,const ArrayBuffer& ln1, const ArrayBuffer& ln2,
  ErrorResult& aUniFFIErrorResult);
};

}  // namespace mozilla::dom

#endif  // mozilla_dom_GeometryScaffolding_h