// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

[ChromeOnly, Exposed=Window]
namespace {{ ci.scaffolding_namespace() }} {
{%- for func in ci.iter_user_ffi_function_definitions() %}
  [Throws]
  {{ func.return_type_name() }} {{ func.nm() }}(
      {%- for arg in func.arguments() %}{{ arg.type_name() }} {{ arg.nm() }}{% if !loop.last %}, {% endif %}{% endfor -%}
    );
{%- endfor %}
};
