// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

#include "nsIGlobalObject.h"
#include "mozilla/MozPromise.h"
#include "mozilla/dom/{{ ci.scaffolding_class() }}.h"
#include "mozilla/dom/OwnedRustBuffer.h"
#include "mozilla/dom/Promise.h"

namespace {{ ci.cpp_namespace() }} {
{%- for func in ci.iter_user_ffi_function_definitions() %}
// For each Rust scaffolding function, define types and functions for calling it
namespace {{ func.cpp_namespace() }} {
using namespace mozilla::dom;
// Arguments to pass to the scaffolding function
struct Args {
    {%- for arg in func.arguments() %}
    {%- match arg.type_() %}
    {%- when FFIType::RustBuffer %}
    // RustBuffer arguments are stored as OwnedRustBuffer instances.  That class takes care of
    // freeing the buffer if the arguments don't get passed to Rust (i.e. intoRustBuffer()
    // isn't called).  This can happen if some of the ArrayBuffer arguments are succuessfully
    // converted, but one fails to convert.
    mozilla::dom::OwnedRustBuffer {{ arg.nm() }};
    {%- else %}
    {{ arg.args_type() }} {{ arg.nm() }};
    {%- endmatch %}
    {%- endfor %}
};

// Return values from the scaffolding function
struct Result {
    {%- if func.has_return_type() %}
    {{ func.rust_return_type() }} mReturnValue;
    {%- endif %}
    RustCallStatus mCallStatus = {};
};

// Convert the arguments we get from JS to arguments to pass to Rust.
//
// On error, an error code will be stored in result.  Make sure to check this before
// passing the args to Invoke().
//
// For async calls this should be called in the main thread, since the GC can
// move the ArrayBuffer pointers while the background task is waiting.
Args PrepareArgs(
    {%- if func.has_args()%}{{ func.input_arg_list() }},{%- else %}{%- endif %}
    mozilla::ErrorResult& aUniFFIError) {
    // Note: Prefix our params and local variables with "uniffi" to avoid name
    // conflicts with the scaffolding function args
    Args uniFFIArgs;

    {%- for arg in func.arguments() %}
    {%- match arg.type_() %}
    {%- when FFIType::RustBuffer %}
    // Convert the ArrayBuffer we get from JS to an OwnedRustBuffer
    {{ arg.nm() }}.ComputeState();
    uniFFIArgs.{{ arg.nm() }} = OwnedRustBuffer({{ arg.nm() }}, aUniFFIError);
    if (aUniFFIError.Failed()) {
        return uniFFIArgs;
    }
    {%- when FFIType::RustArcPtr %}
    // Extract the pointer from the JS::Value using `toPrivate`.
    uniFFIArgs.{{ arg.nm() }} = {{ arg.nm() }}.toPrivate();
    {%- else %}
    uniFFIArgs.{{ arg.nm() }} = {{ arg.nm() }};
    {%- endmatch %}
    {%- endfor %}

    return uniFFIArgs;
}

// Call the scaffolding function
//
// For async calls this should be called in the worker thread
Result Invoke(Args& aArgs) {
    Result result = {};
    {%- if func.has_return_type() %}result.mReturnValue = {%- endif %}::{{ func.rust_name() }}(
         {%- for arg in func.arguments() %}
         {%- match arg.type_() %}
         {%- when FFIType::RustBuffer %}
         // Call intoRustBuffer() to get a `RustBuffer` from an OwnedRustBuffer.  This transfers ownership to Rust,
         // OwnedRustBuffer will no longer try to free it
         aArgs.{{ arg.nm() }}.intoRustBuffer(),
         {%- else %}
         aArgs.{{ arg.nm() }},
         {%- endmatch %}
         {%- endfor %}
         &result.mCallStatus
     );
    return result;
}

// Return the result of the scaffolding call back to JS
void ReturnResult(JSContext* aContext, const Result& aCallResult, RootedDictionary<UniFFIRustCallResult>& aReturnValue) {
    switch (aCallResult.mCallStatus.code) {
        case uniffi::CALL_SUCCESS:
            // Successful call.  Populate data with the return value
            aReturnValue.mCode = uniffi::CALL_SUCCESS;
            {%- match func.return_type() %}
            {%- when Some with (FFIType::RustBuffer) %}
            // RustBuffer return, convert it to an ArrayBuffer
            aReturnValue.mData.setObjectOrNull(OwnedRustBuffer(aCallResult.mReturnValue).intoArrayBuffer(aContext));
            {%- when Some with (FFIType::RustArcPtr) %}
            // Pointer return, use `JS::Value::setPrivate()` to store it
            aReturnValue.mData.setPrivate(aCallResult.mReturnValue);
            {%- when Some with (_) %}
            // Numeric Return
            aReturnValue.mData.setNumber(aCallResult.mReturnValue);
            {%- when None %}
            // Void return
            {%- endmatch %}
            break;

        case uniffi::CALL_ERROR:
            // Rust Err() value.  Populate data with the `RustBuffer` containing the error
            aReturnValue.mCode = uniffi::CALL_ERROR;
            aReturnValue.mData.setObjectOrNull(OwnedRustBuffer(aCallResult.mCallStatus.error_buf).intoArrayBuffer(aContext));
            break;

        default:
            // This indicates a RustError, which shouldn't happen in practice since FF sets panic=abort
            aReturnValue.mCode = uniffi::CALL_INTERNAL_ERROR;
            aReturnValue.mInternalErrorMessage.AssignLiteral(u"Unexpected Error");
            break;
    }
}
}
{%- endfor %}
}

namespace mozilla::dom {

{%- for func in ci.iter_user_ffi_function_definitions() %}
{%- let fully_qualified_name = "{}::{}"|format(ci.scaffolding_class(), func.nm()) %}
using namespace {{ ci.cpp_namespace() }};

{%- if func.is_async() %}
already_AddRefed<Promise> {{ fully_qualified_name }}(const GlobalObject& aUniFFIGlobal,
{%- if func.has_args()%}{{ func.input_arg_list() }},{%- else %}{%- endif %}
 ErrorResult& aUniFFIError) {
    // Note: Prefix our params and local variables with "uniffi" to avoid name
    // conflicts with the scaffolding function args

    // Create the promise that we return to JS
    nsCOMPtr<nsIGlobalObject> uniFFIXPCOMGlobal = do_QueryInterface(aUniFFIGlobal.GetAsSupports());
    RefPtr<Promise> uniFFIReturnPromise = Promise::Create(uniFFIXPCOMGlobal, aUniFFIError);
    if (aUniFFIError.Failed()) {
        return nullptr;
    }

    // Prepare arguments to pass to Rust
    auto uniFFIArgs = {{ func.cpp_namespace() }}::PrepareArgs({% for arg in func.arguments() %}{{ arg.nm() }}, {% endfor %}aUniFFIError);
    if (aUniFFIError.Failed()) {
        return nullptr;
    }

    // Create a second promise that gets resolved by a background task that calls the scaffolding function
    using UniFFITaskPromise = MozPromise<{{ func.cpp_namespace() }}::Result, nsresult, true>;
    RefPtr uniFFITaskPromise = new UniFFITaskPromise::Private(__func__);
    nsresult uniFFIDispatchResult = NS_DispatchBackgroundTask(
            NS_NewRunnableFunction(
                "{{ fully_qualified_name }}",
                [args = std::move(uniFFIArgs), uniFFITaskPromise]() mutable {
                auto result = {{ func.cpp_namespace() }}::Invoke(args);
                uniFFITaskPromise->Resolve(std::move(result), __func__);
            }),
            NS_DISPATCH_EVENT_MAY_BLOCK);
    if (NS_FAILED(uniFFIDispatchResult)) {
        uniFFITaskPromise->Reject(uniFFIDispatchResult, __func__);
    }

    // When the background task promise completes, resolve the JS promise
    uniFFITaskPromise->Then(GetCurrentSerialEventTarget(), __func__,
            [uniFFIXPCOMGlobal, uniFFIReturnPromise](UniFFITaskPromise::ResolveOrRejectValue&& aResult) {
            if (!aResult.IsResolve()) {
                uniFFIReturnPromise->MaybeRejectWithUnknownError("{{ fully_qualified_name }} task dispatch failed");
                return;
            }

            AutoEntryScript aes(uniFFIXPCOMGlobal, "{{ fully_qualified_name }} call resolve");
            RootedDictionary<UniFFIRustCallResult> returnValue(aes.cx());

            {{ func.cpp_namespace() }}::ReturnResult(aes.cx(), aResult.ResolveValue(), returnValue);
            uniFFIReturnPromise->MaybeResolve(returnValue);
            }
    );

    // Return the JS promise, using forget() to convert it to already_AddRefed
    return uniFFIReturnPromise.forget();
}

{%- else %}
void {{ ci.scaffolding_class() }}::{{ func.nm() }}(const GlobalObject& aUniFFIGlobal,
{%- if func.has_args()%}{{ func.input_arg_list() }},{%- else %}{%- endif %}
RootedDictionary<UniFFIRustCallResult>& aUniFFIReturnValue, ErrorResult& aUniFFIError) {
    // Note: Prefix our params and local variables with "uniffi" to avoid name
    // conflicts with the scaffolding function args

    auto uniFFIArgs = {{ func.cpp_namespace() }}::PrepareArgs({% for arg in func.arguments() %}{{ arg.nm() }}, {% endfor %}aUniFFIError);
    if (aUniFFIError.Failed()) {
        return;
    }
    auto uniFFIResult = {{ func.cpp_namespace() }}::Invoke(uniFFIArgs);
    {{ func.cpp_namespace() }}::ReturnResult(aUniFFIGlobal.Context(), uniFFIResult, aUniFFIReturnValue);
}
{%- endif %}

{%- endfor %}

}  // namespace mozilla::dom
