// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

[ChromeOnly, Exposed=Window]
namespace {{ ci.scaffolding_name() }} {
{%- for func in ci.iter_user_ffi_function_definitions() %}
  [Throws]
  {{ func.webidl_return_type() }} {{ func.webidl_name() }}(
      {%- for arg in func.arguments() %}{{ arg.webidl_type() }} {{ arg.webidl_name() }}{% if !loop.last %}, {% endif %}{% endfor -%}
    );
{%- endfor %}
};
