// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

#ifndef mozilla_dom_{{ ci.scaffolding_name() }}_h
#define mozilla_dom_{{ ci.scaffolding_name() }}_h

#include "mozilla/ErrorResult.h"
#include "mozilla/dom/RootedDictionary.h"
#include "mozilla/dom/TypedArray.h"
#include "mozilla/dom/UniFFIRustCallResultBinding.h"
#include "UniFFI.h"

// Scaffolding functions from UniFFI
extern "C" {
{%- for func in ci.iter_user_ffi_function_definitions() %}
{{ func.rust_return_type() }} {{ func.rust_name() }}({{ func.rust_arg_list() }});
{% endfor %}
}

namespace mozilla::dom {

class GlobalObject;

class {{ ci.scaffolding_name() }} {
  public:
  {%- for func in ci.iter_user_ffi_function_definitions() %}

  static {{ func.cpp_return_type() }} {{ func.cpp_name() }}({{ func.cpp_arg_list() }});
  {%- endfor %}
};

}  // namespace mozilla::dom

#endif  // mozilla_dom_{{ ci.scaffolding_name() }}_h
