// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

#ifndef mozilla_dom_GeometryScaffolding_h
#define mozilla_dom_GeometryScaffolding_h

#include "mozilla/ErrorResult.h"
#include "mozilla/dom/TypedArray.h"
#include "mozilla/dom/UniFFIRustCallStatus.h"
#include "UniFFI.h"

// Scaffolding functions from UniFFI
extern "C" {
double geometry_eb69_gradient(RustBuffer, RustCallStatus*);

RustBuffer geometry_eb69_intersection(RustBuffer, RustBuffer, RustCallStatus*);

}

namespace mozilla::dom {

class GlobalObject;

class GeometryScaffolding {
  public:

  static double GeometryEb69Gradient(const GlobalObject& aGlobal, const ArrayBuffer& ln, UniFFIRustCallStatus& status, ErrorResult& aErrorResult);

  static void GeometryEb69Intersection(const GlobalObject& aGlobal, const ArrayBuffer& ln1, const ArrayBuffer& ln2, UniFFIRustCallStatus& status, JS::MutableHandle<JSObject*> aRetVal, ErrorResult& aErrorResult);
};

}  // namespace mozilla::dom

#endif  // mozilla_dom_GeometryScaffolding_h