// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

#ifndef mozilla_dom_GeometryScaffolding_h
#define mozilla_dom_GeometryScaffolding_h

#include "mozilla/ErrorResult.h"
#include "mozilla/dom/RootedDictionary.h"
#include "mozilla/dom/TypedArray.h"
#include "mozilla/dom/UniFFIRustCallResultBinding.h"
#include "UniFFI.h"

// Scaffolding functions from UniFFI
extern "C" {
double geometry_f18a_gradient(RustBuffer, RustCallStatus*);

RustBuffer geometry_f18a_intersection(RustBuffer, RustBuffer, RustCallStatus*);

RustBuffer geometry_f18a_string_round(RustBuffer, RustCallStatus*);

RustBuffer geometry_f18a_string_record_round(RustBuffer, RustCallStatus*);

}

namespace mozilla::dom {

class GlobalObject;

class GeometryScaffolding {
  public:
  static already_AddRefed<Promise> GeometryF18aGradient(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& ln, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> GeometryF18aIntersection(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& ln1, const ArrayBuffer& ln2, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> GeometryF18aStringRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& s, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> GeometryF18aStringRecordRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& p, ErrorResult& aUniFFIErrorResult);
};

}  // namespace mozilla::dom

#endif  // mozilla_dom_GeometryScaffolding_h