// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

[ChromeOnly, Exposed=Window]
namespace GeometryScaffolding {
  [Throws]
  Promise<UniFFIRustCallResult> geometryEb69Gradient(ArrayBuffer ln );
  [Throws]
  Promise<UniFFIRustCallResult> geometryEb69Intersection(ArrayBuffer ln1, ArrayBuffer ln2 );
};