// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

[ChromeOnly, Exposed=Window]
namespace GeometryScaffolding {
  [Throws] double geometryEb69Gradient(ArrayBuffer ln, UniFFIRustCallStatus status);
  [Throws] ArrayBuffer geometryEb69Intersection(ArrayBuffer ln1, ArrayBuffer ln2, UniFFIRustCallStatus status);
};